---
- hosts: localhost
  tasks:
    - name: Clean and Build
      shell: ./gradlew clean build
      args:
        chdir: /home/ravi/Downloads/demo1/demo/

    - name: Run the Application
      shell: java -jar build/libs/demo-0.0.1-SNAPSHOT.jar
      args:
        chdir: /home/ravi/Downloads/demo1/demo/
